import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Glob('*.c') + Glob('*.cpp')

group = DefineGroup('prt/pp', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
